appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: evBPVIJzYSnWKXBccqvRque+vn6/jlH+yYggJk5/iQKRlTvNmRkKgcMymANaiM2yoX/yrCDTLVYwIXStK7HsMsEXZx1OGwIV9M7ZJvI914YgrhR9dmvenDiGHr5hIj+07t7U3oUV+3Rlc2bSxD9fjQGxN55mneLMQ8YeTvoAJyHUqEvobq9tNX6+0k4speJ5TPw7I/mKySWNgvLV7v0JWEx9+UOKD6RocxjAphG9NMHxr4G4rIb1vxv8sks/rx69RXQ5S2AOzlIYE4DV83ufXh2FiT971nmn1dQcVz4mcYFY5iH8Iw87k2DGzTFaNfMdurIUBtGNF/SneZMbcMpDqbaOpWt5YJvLyE2fr7Lu/v3GGRe2v6zU3vM1JepAnW9TqyGvs2kJlg4lZQL0e8fR1ahXd0wrCWnJp5RCHZ0of53wztAgquZPySUICDWKd1wDNmrOSbGApANSu8WFAwCsctrmMmW4k0I1xxQraKhpdd5wsSl2CfwJgN8TsmuLJyTvWzSxN5I6zQzfq/D/aP/hWW75lLRDEIpnNnz+C3C1Tm5NLuWqXykwiDo+Djw4zIH210n4Nc3wo6YUrgflGgvX1keKQgERIV3UPxuqiMaAAJozI24MJ2bzPEOcB6tn1EaHvEacOqqW6kxlJ6ZUtWpSgvi3N+iPPJAm0zzhtKHKEgc=}
conda_forge_output_validation: false
