travis:
  secure:
    BINSTAR_TOKEN: Gspw/UaaGstn3lbixJ6DQCMolvf8avYG2rkPGjxQaK1jawUQg0+kafcpk/5euGjgU6EdWKvhsJ0V4hGSXw4QwCs/FlQiXs2ZQl+Rc6D2yGBvL9gXWIGMUYFeUTN/AjCyPvyrVvTTtlFG0prGMfCbzFKw2xv1IfRvoQ090x83mAbUNqkLWKy2edTW3Wa7GltI/SWwMpOjg7RKCqobEGca8KXiVVT9garLgvJxy8Zn4LucGrXMhDFqVk+gqNizuSLCluRxPpXXqBJQHzcJeqN6Y070Ew2ocOOyGv7y1oqDfQz0DIkNBeZgU2ZgzDTX0WDpQW/kZ2IwCE+H30sqPiJbPU5MMqfsiwnmvGA6Huw9lKKvLf7Pb4LHY+dvVWSJif3VGdvKX8IF1JFaVGdcFDn/FrIxV8g6dnsmP2rGkhMEWygFIu1HiVpudrSWP9aZ6x5GhHqc5pv1jcIHQhy+P473OYtESnja2rLvcNwhQN6NxINa302p0K82nBNkKvn4aqpys5aHqRustXe5qjUwFQXOPydX/gM+Ubu43+wDSQAdwGEwp61AiEJD3MAboTnxK0WshRONIjdSuKXNTt1qI7hjvykGBLeXhjmM+7U0k8a5QUO51j5Wn4nBg8arBRkOVWdS5wauPUIrO/7KV+3ewkgXz8u6hwRIh3t0ssrJZp+uSRc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
